name: main

on:
  push:
    branches: [master]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install

      - name: Checkout
        uses: actions/checkout@v2

      - name: "Populate auth file with CI_URL secret"
        shell: bash
        run: "echo ${{ secrets.CI_URL}} > ./CI_URL.txt"

      - name: "Authenticate CI Sandbox"
        run: "sfdx force:auth:sfdxurl:store -f ./CI_URL.txt -a ci -d"

      - name: 'Create scratch org'
        run: 'sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1'

      - name: 'Push source to scratch org'
        run: 'sfdx force:source:push'

      - name: 'Run Apex tests'
        run: sfdx force:apex:test:run -c -r human -d ./tests/apex -w 20
        
      - name: 'Upload code coverage for Apex to Codecov.io'
        uses: codecov/codecov-action@v2.0.2
        with:
            flags: Apex

      - name: 'Delete scratch org'
        if: always()
        run: 'sfdx force:org:delete -p -u scratch-org'
